export const Iconpe7 = () => (
    <div className="page-wrapper cardhead">
      <div className="content container-fluid">
        <div className="page-header">
          <div className="row">
            <div className="col-sm-12">
              <h3 className="page-title">Pe7 Icon</h3>
              <ul className="breadcrumb">
                <li className="breadcrumb-item">
                  <a href="index.html">Dashboard</a>
                </li>
                <li className="breadcrumb-item active">Pe7 Icon</li>
              </ul>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-md-12">
            <div className="card">
              <div className="card-header">
                <div className="card-title">Pe7 Icon</div>
              </div>
              <div className="card-body">
                <div className="icons-items">
                  <ul className="icons-list">
                    <li>
                      <i
                        className="pe-7s-album"
                        data-bs-toggle="tooltip"
                        title="pe-7s-album"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-arc"
                        data-bs-toggle="tooltip"
                        title="pe-7s-arc"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-back-2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-back-2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-bandaid"
                        data-bs-toggle="tooltip"
                        title="pe-7s-bandaid"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-car"
                        data-bs-toggle="tooltip"
                        title="pe-7s-car"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-diamond"
                        data-bs-toggle="tooltip"
                        title="pe-7s-diamond"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-door-lock"
                        data-bs-toggle="tooltip"
                        title="pe-7s-door-lock"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-eyedropper"
                        data-bs-toggle="tooltip"
                        title="pe-7s-eyedropper"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-female"
                        data-bs-toggle="tooltip"
                        title="pe-7s-female"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-gym"
                        data-bs-toggle="tooltip"
                        title="pe-7s-gym"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-hammer"
                        data-bs-toggle="tooltip"
                        title="pe-7s-hammer"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-headphones"
                        data-bs-toggle="tooltip"
                        title="pe-7s-headphones"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-helm"
                        data-bs-toggle="tooltip"
                        title="pe-7s-helm"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-hourglass"
                        data-bs-toggle="tooltip"
                        title="pe-7s-hourglass"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-leaf"
                        data-bs-toggle="tooltip"
                        title="pe-7s-leaf"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-magic-wand"
                        data-bs-toggle="tooltip"
                        title="pe-7s-magic-wand"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-male"
                        data-bs-toggle="tooltip"
                        title="pe-7s-male"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-map-2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-map-2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-next-2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-next-2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-paint-bucket"
                        data-bs-toggle="tooltip"
                        title="pe-7s-paint-bucket"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-pendrive"
                        data-bs-toggle="tooltip"
                        title="pe-7s-pendrive"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-photo"
                        data-bs-toggle="tooltip"
                        title="pe-7s-photo"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-piggy"
                        data-bs-toggle="tooltip"
                        title="pe-7s-piggy"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-plugin"
                        data-bs-toggle="tooltip"
                        title="pe-7s-plugin"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-refresh-2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-refresh-2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-rocket"
                        data-bs-toggle="tooltip"
                        title="pe-7s-rocket"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-settings"
                        data-bs-toggle="tooltip"
                        title="pe-7s-settings"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-shield"
                        data-bs-toggle="tooltip"
                        title="pe-7s-shield"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-smile"
                        data-bs-toggle="tooltip"
                        title="pe-7s-smile"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-usb"
                        data-bs-toggle="tooltip"
                        title="pe-7s-usb"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-vector"
                        data-bs-toggle="tooltip"
                        title="pe-7s-vector"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-wine"
                        data-bs-toggle="tooltip"
                        title="pe-7s-wine"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-cloud-upload"
                        data-bs-toggle="tooltip"
                        title="pe-7s-cloud-upload"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-cash"
                        data-bs-toggle="tooltip"
                        title="pe-7s-cash"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-close"
                        data-bs-toggle="tooltip"
                        title="pe-7s-close"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-bluetooth"
                        data-bs-toggle="tooltip"
                        title="pe-7s-bluetooth"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-cloud-download"
                        data-bs-toggle="tooltip"
                        title="pe-7s-cloud-download"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-way"
                        data-bs-toggle="tooltip"
                        title="pe-7s-way"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-close-circle"
                        data-bs-toggle="tooltip"
                        title="pe-7s-close-circle"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-id"
                        data-bs-toggle="tooltip"
                        title="pe-7s-id"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-angle-up"
                        data-bs-toggle="tooltip"
                        title="pe-7s-angle-up"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-wristwatch"
                        data-bs-toggle="tooltip"
                        title="pe-7s-wristwatch"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-angle-up-circle"
                        data-bs-toggle="tooltip"
                        title="pe-7s-angle-up-circle"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-world"
                        data-bs-toggle="tooltip"
                        title="pe-7s-world"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-angle-right"
                        data-bs-toggle="tooltip"
                        title="pe-7s-angle-right"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-volume"
                        data-bs-toggle="tooltip"
                        title="pe-7s-volume"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-angle-right-circle"
                        data-bs-toggle="tooltip"
                        title="pe-7s-angle-right-circle"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-users"
                        data-bs-toggle="tooltip"
                        title="pe-7s-users"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-angle-left"
                        data-bs-toggle="tooltip"
                        title="pe-7s-angle-left"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-user-female"
                        data-bs-toggle="tooltip"
                        title="pe-7s-user-female"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-angle-left-circle"
                        data-bs-toggle="tooltip"
                        title="pe-7s-angle-left-circle"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-up-arrow"
                        data-bs-toggle="tooltip"
                        title="pe-7s-up-arrow"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-angle-down"
                        data-bs-toggle="tooltip"
                        title="pe-7s-angle-down"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-switch"
                        data-bs-toggle="tooltip"
                        title="pe-7s-switch"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-angle-down-circle"
                        data-bs-toggle="tooltip"
                        title="pe-7s-angle-down-circle"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-scissors"
                        data-bs-toggle="tooltip"
                        title="pe-7s-scissors"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-wallet"
                        data-bs-toggle="tooltip"
                        title="pe-7s-wallet"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-safe"
                        data-bs-toggle="tooltip"
                        title="pe-7s-safe"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-volume2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-volume2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-volume1"
                        data-bs-toggle="tooltip"
                        title="pe-7s-volume1"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-voicemail"
                        data-bs-toggle="tooltip"
                        title="pe-7s-voicemail"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-video"
                        data-bs-toggle="tooltip"
                        title="pe-7s-video"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-user"
                        data-bs-toggle="tooltip"
                        title="pe-7s-user"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-upload"
                        data-bs-toggle="tooltip"
                        title="pe-7s-upload"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-unlock"
                        data-bs-toggle="tooltip"
                        title="pe-7s-unlock"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-umbrella"
                        data-bs-toggle="tooltip"
                        title="pe-7s-umbrella"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-trash"
                        data-bs-toggle="tooltip"
                        title="pe-7s-trash"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-tools"
                        data-bs-toggle="tooltip"
                        title="pe-7s-tools"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-timer"
                        data-bs-toggle="tooltip"
                        title="pe-7s-timer"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-ticket"
                        data-bs-toggle="tooltip"
                        title="pe-7s-ticket"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-target"
                        data-bs-toggle="tooltip"
                        title="pe-7s-target"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-sun"
                        data-bs-toggle="tooltip"
                        title="pe-7s-sun"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-study"
                        data-bs-toggle="tooltip"
                        title="pe-7s-study"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-stopwatch"
                        data-bs-toggle="tooltip"
                        title="pe-7s-stopwatch"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-star"
                        data-bs-toggle="tooltip"
                        title="pe-7s-star"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-speaker"
                        data-bs-toggle="tooltip"
                        title="pe-7s-speaker"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-signal"
                        data-bs-toggle="tooltip"
                        title="pe-7s-signal"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-shuffle"
                        data-bs-toggle="tooltip"
                        title="pe-7s-shuffle"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-shopbag"
                        data-bs-toggle="tooltip"
                        title="pe-7s-shopbag"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-share"
                        data-bs-toggle="tooltip"
                        title="pe-7s-share"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-server"
                        data-bs-toggle="tooltip"
                        title="pe-7s-server"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-search"
                        data-bs-toggle="tooltip"
                        title="pe-7s-search"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-film"
                        data-bs-toggle="tooltip"
                        title="pe-7s-film"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-science"
                        data-bs-toggle="tooltip"
                        title="pe-7s-science"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-disk"
                        data-bs-toggle="tooltip"
                        title="pe-7s-disk"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-ribbon"
                        data-bs-toggle="tooltip"
                        title="pe-7s-ribbon"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-repeat"
                        data-bs-toggle="tooltip"
                        title="pe-7s-repeat"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-refresh"
                        data-bs-toggle="tooltip"
                        title="pe-7s-refresh"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-add-user"
                        data-bs-toggle="tooltip"
                        title="pe-7s-add-user"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-refresh-cloud"
                        data-bs-toggle="tooltip"
                        title="pe-7s-refresh-cloud"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-paperclip"
                        data-bs-toggle="tooltip"
                        title="pe-7s-paperclip"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-radio"
                        data-bs-toggle="tooltip"
                        title="pe-7s-radio"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-note2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-note2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-print"
                        data-bs-toggle="tooltip"
                        title="pe-7s-print"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-network"
                        data-bs-toggle="tooltip"
                        title="pe-7s-network"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-prev"
                        data-bs-toggle="tooltip"
                        title="pe-7s-prev"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-mute"
                        data-bs-toggle="tooltip"
                        title="pe-7s-mute"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-power"
                        data-bs-toggle="tooltip"
                        title="pe-7s-power"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-medal"
                        data-bs-toggle="tooltip"
                        title="pe-7s-medal"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-portfolio"
                        data-bs-toggle="tooltip"
                        title="pe-7s-portfolio"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-like2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-like2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-plus"
                        data-bs-toggle="tooltip"
                        title="pe-7s-plus"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-left-arrow"
                        data-bs-toggle="tooltip"
                        title="pe-7s-left-arrow"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-play"
                        data-bs-toggle="tooltip"
                        title="pe-7s-play"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-key"
                        data-bs-toggle="tooltip"
                        title="pe-7s-key"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-plane"
                        data-bs-toggle="tooltip"
                        title="pe-7s-plane"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-joy"
                        data-bs-toggle="tooltip"
                        title="pe-7s-joy"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-photo-gallery"
                        data-bs-toggle="tooltip"
                        title="pe-7s-photo-gallery"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-pin"
                        data-bs-toggle="tooltip"
                        title="pe-7s-pin"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-phone"
                        data-bs-toggle="tooltip"
                        title="pe-7s-phone"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-plug"
                        data-bs-toggle="tooltip"
                        title="pe-7s-plug"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-pen"
                        data-bs-toggle="tooltip"
                        title="pe-7s-pen"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-right-arrow"
                        data-bs-toggle="tooltip"
                        title="pe-7s-right-arrow"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-paper-plane"
                        data-bs-toggle="tooltip"
                        title="pe-7s-paper-plane"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-delete-user"
                        data-bs-toggle="tooltip"
                        title="pe-7s-delete-user"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-paint"
                        data-bs-toggle="tooltip"
                        title="pe-7s-paint"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-bottom-arrow"
                        data-bs-toggle="tooltip"
                        title="pe-7s-bottom-arrow"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-notebook"
                        data-bs-toggle="tooltip"
                        title="pe-7s-notebook"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-note"
                        data-bs-toggle="tooltip"
                        title="pe-7s-note"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-next"
                        data-bs-toggle="tooltip"
                        title="pe-7s-next"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-news-paper"
                        data-bs-toggle="tooltip"
                        title="pe-7s-news-paper"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-musiclist"
                        data-bs-toggle="tooltip"
                        title="pe-7s-musiclist"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-music"
                        data-bs-toggle="tooltip"
                        title="pe-7s-music"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-mouse"
                        data-bs-toggle="tooltip"
                        title="pe-7s-mouse"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-more"
                        data-bs-toggle="tooltip"
                        title="pe-7s-more"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-moon"
                        data-bs-toggle="tooltip"
                        title="pe-7s-moon"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-monitor"
                        data-bs-toggle="tooltip"
                        title="pe-7s-monitor"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-micro"
                        data-bs-toggle="tooltip"
                        title="pe-7s-micro"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-menu"
                        data-bs-toggle="tooltip"
                        title="pe-7s-menu"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-map"
                        data-bs-toggle="tooltip"
                        title="pe-7s-map"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-map-marker"
                        data-bs-toggle="tooltip"
                        title="pe-7s-map-marker"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-mail"
                        data-bs-toggle="tooltip"
                        title="pe-7s-mail"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-mail-open"
                        data-bs-toggle="tooltip"
                        title="pe-7s-mail-open"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-mail-open-file"
                        data-bs-toggle="tooltip"
                        title="pe-7s-mail-open-file"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-magnet"
                        data-bs-toggle="tooltip"
                        title="pe-7s-magnet"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-loop"
                        data-bs-toggle="tooltip"
                        title="pe-7s-loop"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-look"
                        data-bs-toggle="tooltip"
                        title="pe-7s-look"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-lock"
                        data-bs-toggle="tooltip"
                        title="pe-7s-lock"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-lintern"
                        data-bs-toggle="tooltip"
                        title="pe-7s-lintern"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-link"
                        data-bs-toggle="tooltip"
                        title="pe-7s-link"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-like"
                        data-bs-toggle="tooltip"
                        title="pe-7s-like"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-light"
                        data-bs-toggle="tooltip"
                        title="pe-7s-light"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-less"
                        data-bs-toggle="tooltip"
                        title="pe-7s-less"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-keypad"
                        data-bs-toggle="tooltip"
                        title="pe-7s-keypad"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-junk"
                        data-bs-toggle="tooltip"
                        title="pe-7s-junk"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-info"
                        data-bs-toggle="tooltip"
                        title="pe-7s-info"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-home"
                        data-bs-toggle="tooltip"
                        title="pe-7s-home"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-help2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-help2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-help1"
                        data-bs-toggle="tooltip"
                        title="pe-7s-help1"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-graph3"
                        data-bs-toggle="tooltip"
                        title="pe-7s-graph3"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-graph2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-graph2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-graph1"
                        data-bs-toggle="tooltip"
                        title="pe-7s-graph1"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-graph"
                        data-bs-toggle="tooltip"
                        title="pe-7s-graph"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-global"
                        data-bs-toggle="tooltip"
                        title="pe-7s-global"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-gleam"
                        data-bs-toggle="tooltip"
                        title="pe-7s-gleam"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-glasses"
                        data-bs-toggle="tooltip"
                        title="pe-7s-glasses"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-gift"
                        data-bs-toggle="tooltip"
                        title="pe-7s-gift"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-folder"
                        data-bs-toggle="tooltip"
                        title="pe-7s-folder"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-flag"
                        data-bs-toggle="tooltip"
                        title="pe-7s-flag"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-filter"
                        data-bs-toggle="tooltip"
                        title="pe-7s-filter"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-file"
                        data-bs-toggle="tooltip"
                        title="pe-7s-file"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-expand1"
                        data-bs-toggle="tooltip"
                        title="pe-7s-expand1"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-exapnd2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-exapnd2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-edit"
                        data-bs-toggle="tooltip"
                        title="pe-7s-edit"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-drop"
                        data-bs-toggle="tooltip"
                        title="pe-7s-drop"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-drawer"
                        data-bs-toggle="tooltip"
                        title="pe-7s-drawer"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-download"
                        data-bs-toggle="tooltip"
                        title="pe-7s-download"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-display2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-display2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-display1"
                        data-bs-toggle="tooltip"
                        title="pe-7s-display1"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-diskette"
                        data-bs-toggle="tooltip"
                        title="pe-7s-diskette"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-date"
                        data-bs-toggle="tooltip"
                        title="pe-7s-date"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-cup"
                        data-bs-toggle="tooltip"
                        title="pe-7s-cup"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-culture"
                        data-bs-toggle="tooltip"
                        title="pe-7s-culture"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-crop"
                        data-bs-toggle="tooltip"
                        title="pe-7s-crop"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-credit"
                        data-bs-toggle="tooltip"
                        title="pe-7s-credit"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-copy-file"
                        data-bs-toggle="tooltip"
                        title="pe-7s-copy-file"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-config"
                        data-bs-toggle="tooltip"
                        title="pe-7s-config"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-compass"
                        data-bs-toggle="tooltip"
                        title="pe-7s-compass"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-comment"
                        data-bs-toggle="tooltip"
                        title="pe-7s-comment"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-coffee"
                        data-bs-toggle="tooltip"
                        title="pe-7s-coffee"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-cloud"
                        data-bs-toggle="tooltip"
                        title="pe-7s-cloud"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-clock"
                        data-bs-toggle="tooltip"
                        title="pe-7s-clock"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-check"
                        data-bs-toggle="tooltip"
                        title="pe-7s-check"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-chat"
                        data-bs-toggle="tooltip"
                        title="pe-7s-chat"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-cart"
                        data-bs-toggle="tooltip"
                        title="pe-7s-cart"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-camera"
                        data-bs-toggle="tooltip"
                        title="pe-7s-camera"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-call"
                        data-bs-toggle="tooltip"
                        title="pe-7s-call"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-calculator"
                        data-bs-toggle="tooltip"
                        title="pe-7s-calculator"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-browser"
                        data-bs-toggle="tooltip"
                        title="pe-7s-browser"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-box2"
                        data-bs-toggle="tooltip"
                        title="pe-7s-box2"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-box1"
                        data-bs-toggle="tooltip"
                        title="pe-7s-box1"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-bookmarks"
                        data-bs-toggle="tooltip"
                        title="pe-7s-bookmarks"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-bicycle"
                        data-bs-toggle="tooltip"
                        title="pe-7s-bicycle"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-bell"
                        data-bs-toggle="tooltip"
                        title="pe-7s-bell"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-battery"
                        data-bs-toggle="tooltip"
                        title="pe-7s-battery"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-ball"
                        data-bs-toggle="tooltip"
                        title="pe-7s-ball"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-back"
                        data-bs-toggle="tooltip"
                        title="pe-7s-back"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-attention"
                        data-bs-toggle="tooltip"
                        title="pe-7s-attention"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-anchor"
                        data-bs-toggle="tooltip"
                        title="pe-7s-anchor"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-albums"
                        data-bs-toggle="tooltip"
                        title="pe-7s-albums"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-alarm"
                        data-bs-toggle="tooltip"
                        title="pe-7s-alarm"
                      />
                    </li>
                    <li>
                      <i
                        className="pe-7s-airplay"
                        data-bs-toggle="tooltip"
                        title="pe-7s-airplay"
                      />
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
  